export enum GameEvent {
    POINTS_CHANGED,
    MOVES_CHANGED,
    NEW_LEVEL,
    PREPARE_GRID,
    GRID_PREPARED,
    BOOSTER_BOMB_STATE_CHANGED,
    BOOSTER_BOMB_QANTITY_CHANGED,
    BOOSTER_RESHUFFLE_QANTITY_CHANGED,
    RESHUFFLE,
    BLOCK_CREATED,
    WIN,
    LOSE,
    BLOCK_CLICK_HAPPENED,
    BOMB_ANIMATION,
    ROCKETV_ANIMATION,
    ROCKETH_ANIMATION
}